export const products = [
  {
    id: 1,
    title: "Running Shoes",
    price: 99,
    image: "/products/product-1.png",
    description:
      "Lightweight running shoes designed for comfort and performance.",
    category: "Footwear",
    rating: 4.3,
    reviews: 120,
    featured: false,
  },
  {
    id: 2,
    title: "Wireless Headphones",
    price: 199,
    image: "/products/product-2.png",
    description: "Noise-cancelling headphones with immersive sound quality.",
    category: "Electronics",
    rating: 4.6,
    reviews: 340,
    featured: false,
  },
  {
    id: 3,
    title: "Backpack",
    price: 129,
    image: "/products/product-3.png",
    description: "Durable backpack perfect for travel and daily use.",
    category: "Accessories",
    rating: 4.2,
    reviews: 95,
    featured: false,
  },
  {
    id: 4,
    title: "Smartwatch",
    price: 249,
    image: "/products/product-4.png",
    description: "Track your fitness and stay connected on the go.",
    category: "Electronics",
    rating: 4.5,
    reviews: 210,
    featured: false,
  },
  {
    id: 5,
    title: "Sunglasses",
    price: 149,
    image: "/products/product-5.png",
    description: "Stylish sunglasses with UV protection.",
    category: "Accessories",
    rating: 4.1,
    reviews: 80,
    featured: false,
  },
  {
    id: 6,
    title: "Digital Camera",
    price: 499,
    image: "/products/product-6.png",
    description: "Capture stunning photos with high resolution.",
    category: "Electronics",
    rating: 4.7,
    reviews: 150,
    featured: false,
  },
  {
    id: 7,
    title: "T-shirt",
    price: 29,
    image: "/products/product-7.png",
    description: "Soft and comfortable cotton t-shirt.",
    category: "Clothing",
    rating: 4.0,
    reviews: 60,
    featured: false,
  },
  {
    id: 9,
    title: "Desk Lamp",
    price: 59,
    image: "/products/product-8.png",
    description: "Modern desk lamp with adjustable brightness.",
    category: "Home",
    rating: 4.3,
    reviews: 70,
    featured: false,
  },
  {
    id: 10,
    title: "Wireless Speaker",
    price: 89,
    image: "/products/product-9.png",
    description: "Portable speaker with powerful sound.",
    category: "Electronics",
    rating: 4.4,
    reviews: 180,
    featured: false,
  },
  {
    id: 11,
    title: "Travel Mug",
    price: 25,
    image: "/products/product-10.png",
    description: "Keep your drinks hot or cold on the go.",
    category: "Home",
    rating: 4.2,
    reviews: 110,
    featured: false,
  },
  {
    id: 8,
    title: "Smartphone",
    price: 699,
    image: "/products/product-11.png",
    description:
      "Latest smartphone with cutting-edge features and performance.",
    category: "Electronics",
    rating: 4.8,
    reviews: 520,
    featured: true,
  },
];
